# Generated by Django 6.0.2 on 2026-02-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('NewCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newcategory')),
            ],
        ),
    ]
