# Generated by Django 6.0.2 on 2026-02-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newcats/'),
        ),
        migrations.AlterField(
            model_name='newsubcategory',
            name='NewCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatall', to='app.newcategory'),
        ),
    ]
