# Generated by Django 6.0.2 on 2026-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newcategory_image_alter_newsubcategory_newcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsubcategory',
            name='NewCategory',
        ),
        migrations.DeleteModel(
            name='NewCategory',
        ),
        migrations.DeleteModel(
            name='NewSubCategory',
        ),
    ]
