# Generated by Django 6.0.2 on 2026-02-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_alter_subcategory_category_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivalProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='new_arrivals/')),
                ('new_arrival_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_arrival_images', to='app.newarrivalproducts')),
            ],
        ),
    ]
