# Generated by Django 6.0.2 on 2026-02-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_newarrivalproducts_newarrivalproductimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewArrivalProducts',
            new_name='NewArrivalProduct',
        ),
    ]
