# Generated by Django 6.0.2 on 2026-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_newarrivalproducts_newarrivalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_no', models.CharField(max_length=50)),
                ('banner_img', models.ImageField(upload_to='banners/')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_desc', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
