# Generated by Django 6.0.2 on 2026-03-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivalproductimage',
            name='new_arrival_product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='NewArrivalProduct',
        ),
        migrations.DeleteModel(
            name='NewArrivalProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
