# Generated by Django 6.0.2 on 2026-03-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_newarrivalproductimage_new_arrival_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='is_new_arrival',
        ),
    ]
