# Generated by Django 6.0.2 on 2026-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_inventory_category_inventory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sub_category',
        ),
    ]
