# Generated by Django 6.0.2 on 2026-03-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_inventory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='app.subcategory'),
        ),
    ]
