# Generated by Django 6.0.2 on 2026-03-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_inventory_category_inventory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='p_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_gallery', models.ImageField(blank=True, null=True, upload_to='prod_gallery/')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_gallery', to='app.inventory')),
            ],
        ),
    ]
