# Generated by Django 6.0.2 on 2026-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], max_length=20),
        ),
    ]
