# Generated by Django 6.0.2 on 2026-03-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
